#ifndef MATRIXERRORS_H
#define MATRIXERRORS_H

typedef enum {
    MATRIX_OPERATION_OK = 0,
    MEMORY_ALLOCATION_FAILED = 100,
    MATRIX_NOT_DEFINED = 200,
    OPERATION_NOT_DEFINED = 201,
    INCOMPATIBLE_MATRIX_TYPES = 300,
    INVALID_MATRIX_SIZE = 400,
    INVALID_MATRIX_INDEX = 401,
    INVALID_TYPE_INFO = 402,
    MATRIX_SIZE_MISMATCH = 403
} MatrixErrors;

#endif // MATRIXERRORS_H